name: Build and Deploy DevHub Backend

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push Docker Image
        env:
          ECR_REPOSITORY: devhub-backend
          ECR_REGISTRY: 911167909056.dkr.ecr.us-east-2.amazonaws.com
        run: |
          docker build -f backend/Dockerfile -t $ECR_REPOSITORY backend/
          docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # IMPORTANT: This step is at the same indentation level as the build step
      - name: Deploy ECS Task Definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          # This references your local JSON file with the full ECS task definition
          task-definition: ecs-task-def.json
          # Optionally override the container image. If you do, add these lines:
          container-image-name: devhub-backend
          container-image-uri: 911167909056.dkr.ecr.us-east-2.amazonaws.com/devhub-backend:latest
          
          service: devhub-backend-service
          cluster: DevHubCluster
          wait-for-service-stability: true
